import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { towerModel,enemyModel,tree,flower,cottage,ball,cylinder,mesh,disposeGroup } from './models.js';
import { TOWERS,LEVELS,waveRoster } from './data.js';

export class Game{
 constructor(canvas,sound,events){
 this.canvas=canvas;this.sound=sound;this.events=events;this.scene=new THREE.Scene();this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
 this.camera=new THREE.OrthographicCamera(-14,14,10,-10,.1,120);this.camera.position.set(17,21,25);this.camera.lookAt(0,0,0);this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.enablePan=false;this.controls.minZoom=.7;this.controls.maxZoom=1.8;this.controls.minPolarAngle=.15;this.controls.maxPolarAngle=Math.PI*.43;this.controls.target.set(0,0,0);this.controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
 this.scene.add(new THREE.AmbientLight('#fff9eb',1.7));const sun=new THREE.DirectionalLight('#fff2dc',2.7);sun.position.set(-9,18,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-17,right:17,top:17,bottom:-17,near:.5,far:60});sun.shadow.normalBias=.04;sun.shadow.bias=-.0003;sun.shadow.radius=4;this.scene.add(sun);const fill=new THREE.DirectionalLight('#d6e7ee',1.2);fill.position.set(10,8,-10);this.scene.add(fill);
 this.world=new THREE.Group();this.scene.add(this.world);this.dynamic=new THREE.Group();this.scene.add(this.dynamic);this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);this.point=new THREE.Vector3();this.pads=[];this.towers=[];this.enemies=[];this.shots=[];this.particles=[];this.selectedType=null;this.selectedTower=null;this.paused=false;this.speed=1;this.time=0;this.last=performance.now();this.hover=-1;
 this.range=new THREE.Mesh(new THREE.RingGeometry(.985,1,80),new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));this.range.rotation.x=-Math.PI/2;this.range.position.y=.19;this.range.visible=false;this.scene.add(this.range);
 this.rangeFill=new THREE.Mesh(new THREE.CircleGeometry(1,80),new THREE.MeshBasicMaterial({color:'#eef5cb',transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false}));this.rangeFill.rotation.x=-Math.PI/2;this.rangeFill.position.y=.18;this.rangeFill.visible=false;this.scene.add(this.rangeFill);
 canvas.addEventListener('pointerdown',e=>{this.down={x:e.clientX,y:e.clientY};this.sound.unlock()});canvas.addEventListener('pointermove',e=>this.move(e));canvas.addEventListener('pointerleave',()=>{this.hover=-1;this.updatePreview()});canvas.addEventListener('pointerup',e=>{if(this.down&&Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)<7){this.move(e);this.click()}this.down=null});canvas.addEventListener('contextmenu',e=>{e.preventDefault();this.select(null)});
 this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.resize();this.loop=this.loop.bind(this);this.frame=requestAnimationFrame(this.loop);
 }
 emit(){this.events.update?.(this)}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);const aspect=w/h;const half=Math.max(9.2,13.5/aspect);this.camera.left=-half*aspect;this.camera.right=half*aspect;this.camera.top=half;this.camera.bottom=-half;this.camera.updateProjectionMatrix()}
 load(index){this.levelIndex=index;this.level=LEVELS[index];this.gold=this.level.gold;this.hp=this.level.hp;this.wave=0;this.active=false;this.finished=false;this.paused=false;this.speed=1;this.kills=0;this.towers=[];this.enemies=[];this.shots=[];this.particles=[];this.queue=[];this.hover=-1;this.selectedTower=null;this.select(null,false);disposeGroup(this.world);disposeGroup(this.dynamic);this.pads=[];this.scene.background=new THREE.Color(this.level.sky);this.scene.fog=new THREE.Fog(this.level.sky,45,100);
 const island=new THREE.Group();this.world.add(island);
 const rounded=(w,h,r)=>{const s=new THREE.Shape();s.moveTo(-w/2+r,-h/2);s.lineTo(w/2-r,-h/2);s.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);s.lineTo(w/2,h/2-r);s.quadraticCurveTo(w/2,h/2,w/2-r,h/2);s.lineTo(-w/2+r,h/2);s.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);s.lineTo(-w/2,-h/2+r);s.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);return s};
 const slab=(w,h,y,depth,color,r)=>{const m=mesh(new THREE.ExtrudeGeometry(rounded(w,h,r),{depth,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.18,bevelThickness:.16,curveSegments:8}),color,island,0,y,0);m.rotation.x=-Math.PI/2;return m};
 slab(20.8,13.2,-1.25,.85,'#c6b393',1.5);slab(21,13.5,-.48,.35,this.level.ground,1.5);slab(20.3,12.8,-1.55,.3,'#b3a286',1.5);
 const floor=mesh(new THREE.PlaneGeometry(200,200),this.level.sky,this.world,0,-2.7,0);floor.rotation.x=-Math.PI/2;floor.castShadow=false;
 this.path=this.level.path.map(p=>new THREE.Vector3(p[0],.13,p[1]));this.segments=[];this.totalLength=0;for(let i=1;i<this.path.length;i++){const length=this.path[i].distanceTo(this.path[i-1]);this.segments.push({a:this.path[i-1],b:this.path[i],length,start:this.totalLength});this.totalLength+=length}
 const pathTiles=new Set();for(const s of this.segments){for(let d=0;d<=s.length;d+=.5){const p=s.a.clone().lerp(s.b,d/s.length);const key=Math.round(p.x)+','+Math.round(p.z);if(pathTiles.has(key))continue;pathTiles.add(key);const tile=mesh(new THREE.BoxGeometry(1.04,.12,1.04),this.level.theme==='snow'?'#eff1dc':'#e8d8b3',island,Math.round(p.x),.03,Math.round(p.z));tile.castShadow=false}}
 this.level.spots.forEach(([x,z],i)=>{const pad=cylinder(island,'#d9dda8',x,.09,z,.68,.73,.12,32);pad.userData.spot=i;this.pads.push(pad);const ring=mesh(new THREE.TorusGeometry(.53,.024,6,32),'#f4f1d3',island,x,.17,z);ring.rotation.x=-Math.PI/2;mesh(new THREE.BoxGeometry(.28,.018,.055),'#f5f3d9',island,x,.18,z);mesh(new THREE.BoxGeometry(.055,.018,.28),'#f5f3d9',island,x,.18,z)});
 this.level.trees.forEach(([x,z],i)=>tree(island,x,z,.8+(i%3)*.2,this.level.theme==='snow'?'#a8c8b6':this.level.theme==='grove'?'#acb16b':'#8fae72'));
 const rand=(n)=>{const v=Math.sin(n*127.1+index*44)*43758.5453;return v-Math.floor(v)};
 for(let i=0;i<100;i++){const x=(rand(i+1)-.5)*19,z=(rand(i+200)-.5)*11.5;const p=new THREE.Vector3(x,.13,z);if(this.segments.some(s=>new THREE.Line3(s.a,s.b).closestPointToPoint(p,true,new THREE.Vector3()).distanceTo(p)<1)||this.level.spots.some(([sx,sz])=>Math.hypot(sx-x,sz-z)<1))continue;if(i%3===0)flower(island,x,z,i%2?'#fff4d2':'#eebea0',.65+rand(i+30)*.4);else{const rock=ball(island,i%5===0?'#c9cead':this.level.theme==='snow'?'#e5eee0':'#b5c78f',x,.1,z,.1+rand(i+40)*.18,.1,.18);rock.rotation.y=i}}
 for(const [x,z] of [[-9,-1.5],[-4,5.2],[7,2.6]]){ball(island,'#a5b980',x,.21,z,.45,.24,.37);ball(island,'#b6c791',x+.3,.2,z+.1,.3,.22,.3)}
 if(this.level.theme==='grove'){for(const [x,z] of [[-8,4],[-7,4.5],[7,-4],[-2,-5]]){const deco=towerModel('mushroom');deco.position.set(x,0,z);deco.scale.setScalar(.5);island.add(deco)}}
 const end=this.path.at(-1);cottage(island,end.x+.3,end.z);const start=this.path[0];cylinder(island,'#aa9068',start.x+.35,.65,start.z-.85,.045,.045,1.3,8);const flag=mesh(new THREE.BoxGeometry(.7,.4,.035),'#d18c6c',island,start.x+.69,1.09,start.z-.85);flag.rotation.y=.2;
 // Two complimentary guardians make the first battlefield immediately playable.
 this.addTower('pea',1,true);this.addTower('mushroom',5,true);this.setView('3d',false);this.emit();
 }
 addTower(type,spot,free=false){if(!free&&(this.gold<TOWERS[type].cost||this.towers.some(t=>t.spot===spot)))return false;const [x,z]=this.level.spots[spot];const model=towerModel(type);model.position.set(x,.18,z);model.rotation.y=.3;this.dynamic.add(model);const tower={type,spot,model,level:1,cooldown:0,spent:TOWERS[type].cost};this.towers.push(tower);if(!free){this.gold-=TOWERS[type].cost;this.sound.play('build');this.burst(new THREE.Vector3(x,.5,z),'#f7dda0',14);this.events.toast?.(`${TOWERS[type].name}準備好了！`)}return tower}
 move(event){if(!this.level)return;const r=this.canvas.getBoundingClientRect();this.pointer.set((event.clientX-r.left)/r.width*2-1,-((event.clientY-r.top)/r.height)*2+1);this.ray.setFromCamera(this.pointer,this.camera);if(!this.ray.ray.intersectPlane(this.plane,this.point))return;this.hover=this.level.spots.findIndex(([x,z])=>Math.hypot(x-this.point.x,z-this.point.z)<.9);this.updatePreview()}
 updatePreview(){if(!this.level)return;const occupied=this.towers.find(t=>t.spot===this.hover);for(let i=0;i<this.pads.length;i++){this.pads[i].scale.setScalar(i===this.hover?1.07:1)}if(this.ghost)this.ghost.visible=false;if(this.selectedType&&this.hover>=0&&!occupied){const [x,z]=this.level.spots[this.hover];if(this.ghost){this.ghost.visible=true;this.ghost.position.set(x,.18,z)}this.showRange(x,z,TOWERS[this.selectedType].range);this.canvas.style.cursor='crosshair'}else if(this.selectedTower){const [x,z]=this.level.spots[this.selectedTower.spot];this.showRange(x,z,this.towerStats(this.selectedTower).range)}else{this.range.visible=false;this.rangeFill.visible=false;this.canvas.style.cursor=occupied||this.hover>=0?'pointer':this.selectedType?'crosshair':'grab'}}
 showRange(x,z,r){this.range.visible=true;this.rangeFill.visible=true;this.range.position.set(x,.19,z);this.rangeFill.position.set(x,.185,z);this.range.scale.setScalar(r);this.rangeFill.scale.setScalar(r)}
 select(type,emit=true){this.selectedType=type;this.selectedTower=null;if(this.ghost){this.scene.remove(this.ghost);this.ghost.traverse(o=>{if(o.material)o.material.dispose()});disposeGroup(this.ghost);this.ghost=null}if(type){this.ghost=towerModel(type);this.ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.55;o.castShadow=false}});this.ghost.visible=false;this.scene.add(this.ghost)}this.canvas.classList.toggle('placing',!!type);this.updatePreview();if(emit)this.emit()}
 click(){if(this.finished||this.paused)return;if(this.hover<0){if(this.selectedTower){this.selectedTower=null;this.emit();this.updatePreview()}return}const tower=this.towers.find(t=>t.spot===this.hover);if(tower){this.select(null,false);this.selectedTower=tower;this.sound.play('click');this.updatePreview();this.emit()}else if(this.selectedType){if(this.gold<TOWERS[this.selectedType].cost){this.events.toast?.('陽光幣不足，再擊退一些小怪吧！');return}this.addTower(this.selectedType,this.hover);this.select(null)}else this.events.toast?.('先從右方挑選一位守衛，再點擊這裡種下！')}
 towerStats(tower){const data=TOWERS[tower.type];return {...data,damage:Math.round(data.damage*(1+(tower.level-1)*.65)),range:data.range+(tower.level-1)*.45,interval:data.interval/(1+(tower.level-1)*.12)}}
 upgrade(){const t=this.selectedTower;if(!t||t.level>=3||this.finished)return;const cost=Math.round(TOWERS[t.type].cost*.75*t.level);if(this.gold<cost){this.events.toast?.('陽光幣不足，先讓守衛再努力一下！');return}this.gold-=cost;t.spent+=cost;t.level++;const old=t.model;const model=towerModel(t.type,t.level);model.position.copy(old.position);model.rotation.copy(old.rotation);this.dynamic.remove(old);disposeGroup(old);this.dynamic.add(model);t.model=model;this.sound.play('build');this.burst(model.position.clone().add(new THREE.Vector3(0,1,0)),'#ffdf87',20);this.updatePreview();this.emit()}
 sell(){const t=this.selectedTower;if(!t||this.finished)return;this.gold+=Math.floor(t.spent*.65);this.dynamic.remove(t.model);disposeGroup(t.model);this.towers.splice(this.towers.indexOf(t),1);this.selectedTower=null;this.sound.play('coin');this.updatePreview();this.emit()}
 startWave(){if(this.active||this.finished||this.paused)return;this.select(null,false);this.wave++;this.queue=waveRoster(this.levelIndex,this.wave);this.spawnTimer=.25;this.active=true;this.sound.play('start');this.events.banner?.(`第 ${this.wave} 波 · ${this.wave===this.level.waves?'大魔王來搗蛋了！':'小怪來啦！'}`);this.emit()}
 spawn(spec){const model=enemyModel(spec.kind);this.dynamic.add(model);const hp=spec.hp*(spec.kind==='boss'?4:spec.kind==='fast'?.75:1);const e={...spec,hp,maxHp:hp,speed:spec.speed*(spec.kind==='fast'?1.55:spec.kind==='boss'?.75:1),distance:0,slow:0,model,dead:false,phase:Math.random()*Math.PI*2};const bar=new THREE.Group();const bg=new THREE.Mesh(new THREE.PlaneGeometry(.72,.09),new THREE.MeshBasicMaterial({color:'#7c896c',depthTest:false}));const fg=new THREE.Mesh(new THREE.PlaneGeometry(.68,.055),new THREE.MeshBasicMaterial({color:'#aee57f',depthTest:false}));fg.position.z=.002;bar.add(bg,fg);bar.position.y=spec.kind==='boss'?2.05:1.3;model.add(bar);e.bar=bar;e.barFill=fg;this.enemies.push(e);this.moveEnemy(e,0)}
 moveEnemy(e,dt){e.slow=Math.max(0,e.slow-dt);e.distance+=dt*e.speed*(e.slow>0?.45:1);const s=this.segments.find(s=>e.distance<=s.start+s.length)||this.segments.at(-1);const p=s.a.clone().lerp(s.b,Math.min(1,(e.distance-s.start)/s.length));e.model.position.copy(p);e.model.position.y+=Math.abs(Math.sin(this.time*8+e.phase))*.1;e.model.rotation.y=Math.atan2(s.b.x-s.a.x,s.b.z-s.a.z);e.bar.quaternion.copy(this.camera.quaternion);e.bar.rotateY(-e.model.rotation.y);e.barFill.scale.x=Math.max(0,e.hp/e.maxHp);e.barFill.position.x=-(1-e.hp/e.maxHp)*.34;if(e.distance>=this.totalLength-.55){e.dead=true;this.hp=Math.max(0,this.hp-(e.kind==='boss'?4:1));this.sound.play('hurt');this.emit();if(this.hp<=0)this.end(false)}}
 fire(t,e){const stats=this.towerStats(t),p=t.model.position.clone().add(new THREE.Vector3(0,1.4,0));const color=TOWERS[t.type].color;const obj=t.type==='frost'?mesh(new THREE.OctahedronGeometry(.16),color,this.dynamic):ball(this.dynamic,color,0,0,0,t.type==='mushroom'?.21:.14);obj.position.copy(p);this.shots.push({model:obj,target:e,start:p,age:0,duration:t.type==='mushroom'?.48:.23,type:t.type,damage:stats.damage});t.cooldown=stats.interval;this.sound.play(t.type);t.recoil=.12}
 hit(shot){const target=shot.target;if(shot.type==='mushroom'){for(const e of this.enemies){if(!e.dead&&e.model.position.distanceTo(shot.model.position)<1.8)this.damage(e,shot.damage)}this.burst(shot.model.position,'#f2b66e',13)}else if(!target.dead){this.damage(target,shot.damage);if(shot.type==='frost')target.slow=2.5;this.burst(shot.model.position,shot.type==='frost'?'#bfede6':'#cbdf8d',5)}}
 damage(e,value){e.hp-=value;if(e.hp<=0&&!e.dead){e.dead=true;this.kills++;this.gold+=e.kind==='boss'?50:12;this.sound.play('coin');this.burst(e.model.position.clone().add(new THREE.Vector3(0,.4,0)),'#f5d279',7);this.emit()}}
 burst(pos,color,count){for(let i=0;i<count;i++){const m=ball(this.dynamic,color,pos.x,pos.y,pos.z,.06+Math.random()*.05);this.particles.push({model:m,velocity:new THREE.Vector3((Math.random()-.5)*3,1+Math.random()*2,(Math.random()-.5)*3),life:.45+Math.random()*.3,total:.75})}}
 removeDynamic(obj){this.dynamic.remove(obj);obj.traverse(o=>{if(o.material&&!Array.isArray(o.material)&&o.material.isMeshBasicMaterial)o.material.dispose()});disposeGroup(obj)}
 tick(dt){if(!this.level||this.paused||this.finished)return;this.time+=dt;for(const t of this.towers){t.model.userData.head.position.y=Math.sin(this.time*2+t.spot)*.035;if(t.recoil>0){t.recoil-=dt;t.model.userData.head.scale.setScalar(1+Math.max(0,t.recoil)*.3)}else t.model.userData.head.scale.setScalar(1)}
 if(this.active){this.spawnTimer-=dt;if(this.queue.length&&this.spawnTimer<=0){this.spawn(this.queue.shift());this.spawnTimer=.9+Math.max(0,1.2-this.wave*.13)}for(const e of this.enemies){if(!e.dead)this.moveEnemy(e,dt);if(this.finished)break}if(this.finished)return;
 for(const t of this.towers){t.cooldown-=dt;const stats=this.towerStats(t);const target=this.enemies.filter(e=>!e.dead&&e.model.position.distanceTo(t.model.position)<stats.range).sort((a,b)=>b.distance-a.distance)[0];if(target){const delta=target.model.position.clone().sub(t.model.position);const desired=Math.atan2(delta.x,delta.z);const diff=Math.atan2(Math.sin(desired-t.model.rotation.y),Math.cos(desired-t.model.rotation.y));t.model.rotation.y+=diff*Math.min(1,dt*12);if(t.cooldown<=0)this.fire(t,target)}}}
 for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];s.age+=dt;const k=Math.min(1,s.age/s.duration);s.model.position.copy(s.start).lerp(s.target.model.position.clone().add(new THREE.Vector3(0,.5,0)),k);if(s.type==='mushroom')s.model.position.y+=Math.sin(k*Math.PI)*2;s.model.rotation.y+=dt*5;if(k>=1){this.hit(s);this.removeDynamic(s.model);this.shots.splice(i,1)}}
 for(let i=this.enemies.length-1;i>=0;i--){if(this.enemies[i].dead){this.removeDynamic(this.enemies[i].model);this.enemies.splice(i,1)}}
 for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.life-=dt;p.velocity.y-=dt*6;p.model.position.addScaledVector(p.velocity,dt);p.model.scale.setScalar(Math.max(0,p.life/p.total)*.1);if(p.life<=0){this.removeDynamic(p.model);this.particles.splice(i,1)}}
 if(this.active&&!this.queue.length&&!this.enemies.length&&!this.shots.length){this.active=false;this.gold+=this.level.reward;if(this.wave>=this.level.waves)this.end(true);else{this.sound.play('build');this.events.banner?.(`守住了！ +${this.level.reward} 陽光幣`);this.emit()}}
 }
 end(won){if(this.finished)return;this.finished=true;this.active=false;this.select(null,false);this.sound.play(won?'win':'lose');this.emit();this.events.end?.({won,level:this.levelIndex,hp:this.hp,kills:this.kills,stars:this.hp>=18?3:this.hp>=10?2:1})}
 togglePause(){if(this.finished)return;this.paused=!this.paused;this.emit()}
 toggleSpeed(){this.speed=this.speed===1?2:1;this.emit()}
 setView(view,animate=true){this.view=view;const target=view==='2d'?new THREE.Vector3(0,34,.01):new THREE.Vector3(17,21,25);this.controls.enableRotate=view!=='2d';if(animate)this.cameraTween={from:this.camera.position.clone(),to:target,t:0};else{this.camera.position.copy(target);this.camera.zoom=1;this.camera.updateProjectionMatrix();this.controls.update()}this.events.view?.(view)}
 zoom(delta){this.camera.zoom=THREE.MathUtils.clamp(this.camera.zoom+delta,.7,1.8);this.camera.updateProjectionMatrix()}
 loop(now){this.frame=requestAnimationFrame(this.loop);const dt=Math.min((now-this.last)/1000,.06);this.last=now;if(this.cameraTween){this.cameraTween.t=Math.min(1,this.cameraTween.t+dt*2.5);const t=this.cameraTween.t;this.camera.position.lerpVectors(this.cameraTween.from,this.cameraTween.to,t*t*(3-2*t));if(t>=1)this.cameraTween=null}this.controls.update();this.tick(dt*this.speed);this.renderer.render(this.scene,this.camera)}
}
