import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { towerModel,enemyModel,tree,flower,cottage,ball,cylinder,mesh,disposeGroup } from './models.js';
import { TOWERS,LEVELS,ENEMIES,waveRoster } from './data.js';

export class Game{
 constructor(canvas,sound,events){
 this.unlockedTowers=['pea','mushroom','frost'];this.canvas=canvas;this.sound=sound;this.events=events;this.scene=new THREE.Scene();this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
 this.camera=new THREE.OrthographicCamera(-14,14,10,-10,.1,120);this.camera.position.set(17,21,25);this.camera.lookAt(0,0,0);this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.enablePan=false;this.controls.minZoom=.7;this.controls.maxZoom=1.8;this.controls.minPolarAngle=.15;this.controls.maxPolarAngle=Math.PI*.43;this.controls.target.set(0,0,0);this.controls.mouseButtons={LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.ROTATE};
 this.scene.add(new THREE.AmbientLight('#fff9eb',1.7));const sun=new THREE.DirectionalLight('#fff2dc',2.7);sun.position.set(-9,18,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-17,right:17,top:17,bottom:-17,near:.5,far:60});sun.shadow.normalBias=.04;sun.shadow.bias=-.0003;sun.shadow.radius=4;this.scene.add(sun);const fill=new THREE.DirectionalLight('#d6e7ee',1.2);fill.position.set(10,8,-10);this.scene.add(fill);
 this.world=new THREE.Group();this.scene.add(this.world);this.dynamic=new THREE.Group();this.scene.add(this.dynamic);this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);this.point=new THREE.Vector3();this.pads=[];this.towers=[];this.enemies=[];this.shots=[];this.particles=[];this.effects=[];this.fusionSelected=[];this.selectedType=null;this.selectedTower=null;this.paused=false;this.speed=1;this.time=0;this.last=performance.now();this.hover=-1;
 this.range=new THREE.Mesh(new THREE.RingGeometry(.985,1,80),new THREE.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));this.range.rotation.x=-Math.PI/2;this.range.position.y=.19;this.range.visible=false;this.scene.add(this.range);
 this.rangeFill=new THREE.Mesh(new THREE.CircleGeometry(1,80),new THREE.MeshBasicMaterial({color:'#eef5cb',transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false}));this.rangeFill.rotation.x=-Math.PI/2;this.rangeFill.position.y=.18;this.rangeFill.visible=false;this.scene.add(this.rangeFill);
 canvas.addEventListener('pointerdown',e=>{this.down={x:e.clientX,y:e.clientY};this.sound.unlock()});canvas.addEventListener('pointermove',e=>this.move(e));canvas.addEventListener('pointerleave',()=>{this.hover=-1;this.updatePreview()});canvas.addEventListener('pointerup',e=>{if(this.down&&Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)<7){this.move(e);this.click()}this.down=null});canvas.addEventListener('contextmenu',e=>{e.preventDefault();this.select(null)});
 this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.resize();this.loop=this.loop.bind(this);this.frame=requestAnimationFrame(this.loop);
 }
 emit(){this.events.update?.(this)}
 resize(){const w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h,false);const aspect=w/h;const half=Math.max(9.2,13.5/aspect);this.camera.left=-half*aspect;this.camera.right=half*aspect;this.camera.top=half;this.camera.bottom=-half;this.camera.updateProjectionMatrix()}
 load(index){if(!LEVELS[index])return;this.levelIndex=index;this.level=LEVELS[index];this.gold=this.level.gold;this.hp=this.level.hp;this.wave=0;this.active=false;this.finished=false;this.paused=false;this.speed=1;this.kills=0;this.towers=[];this.enemies=[];this.shots=[];this.particles=[];this.effects=[];this.fusionSelected=[];this.queue=[];this.hover=-1;this.selectedTower=null;this.select(null,false);disposeGroup(this.world);disposeGroup(this.dynamic);this.pads=[];this.scene.background=new THREE.Color(this.level.sky);this.scene.fog=new THREE.Fog(this.level.sky,45,100);
 const island=new THREE.Group();this.world.add(island);
 const rounded=(w,h,r)=>{const s=new THREE.Shape();s.moveTo(-w/2+r,-h/2);s.lineTo(w/2-r,-h/2);s.quadraticCurveTo(w/2,-h/2,w/2,-h/2+r);s.lineTo(w/2,h/2-r);s.quadraticCurveTo(w/2,h/2,w/2-r,h/2);s.lineTo(-w/2+r,h/2);s.quadraticCurveTo(-w/2,h/2,-w/2,h/2-r);s.lineTo(-w/2,-h/2+r);s.quadraticCurveTo(-w/2,-h/2,-w/2+r,-h/2);return s};
 const slab=(w,h,y,depth,color,r)=>{const m=mesh(new THREE.ExtrudeGeometry(rounded(w,h,r),{depth,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.18,bevelThickness:.16,curveSegments:8}),color,island,0,y,0);m.rotation.x=-Math.PI/2;return m};
 slab(20.8,13.2,-1.25,.85,'#c6b393',1.5);slab(21,13.5,-.48,.35,this.level.ground,1.5);slab(20.3,12.8,-1.55,.3,'#b3a286',1.5);
 const floor=mesh(new THREE.PlaneGeometry(200,200),this.level.sky,this.world,0,-2.7,0);floor.rotation.x=-Math.PI/2;floor.castShadow=false;
 this.path=this.level.path.map(p=>new THREE.Vector3(p[0],.13,p[1]));this.segments=[];this.totalLength=0;for(let i=1;i<this.path.length;i++){const length=this.path[i].distanceTo(this.path[i-1]);this.segments.push({a:this.path[i-1],b:this.path[i],length,start:this.totalLength});this.totalLength+=length}
 const pathTiles=new Set();for(const s of this.segments){for(let d=0;d<=s.length;d+=.5){const p=s.a.clone().lerp(s.b,d/s.length);const key=Math.round(p.x)+','+Math.round(p.z);if(pathTiles.has(key))continue;pathTiles.add(key);const tile=mesh(new THREE.BoxGeometry(1.04,.12,1.04),this.level.theme==='snow'?'#eff1dc':'#e8d8b3',island,Math.round(p.x),.03,Math.round(p.z));tile.castShadow=false}}
 this.level.spots.forEach(([x,z],i)=>{const pad=cylinder(island,'#d9dda8',x,.09,z,.68,.73,.12,32);pad.userData.spot=i;this.pads.push(pad);const ring=mesh(new THREE.TorusGeometry(.53,.024,6,32),'#f4f1d3',island,x,.17,z);ring.rotation.x=-Math.PI/2;mesh(new THREE.BoxGeometry(.28,.018,.055),'#f5f3d9',island,x,.18,z);mesh(new THREE.BoxGeometry(.055,.018,.28),'#f5f3d9',island,x,.18,z)});
 this.level.trees.forEach(([x,z],i)=>tree(island,x,z,.8+(i%3)*.2,this.level.theme==='snow'?'#a8c8b6':this.level.theme==='grove'?'#acb16b':'#8fae72'));
 const rand=(n)=>{const v=Math.sin(n*127.1+index*44)*43758.5453;return v-Math.floor(v)};
 for(let i=0;i<100;i++){const x=(rand(i+1)-.5)*19,z=(rand(i+200)-.5)*11.5;const p=new THREE.Vector3(x,.13,z);if(this.segments.some(s=>new THREE.Line3(s.a,s.b).closestPointToPoint(p,true,new THREE.Vector3()).distanceTo(p)<1)||this.level.spots.some(([sx,sz])=>Math.hypot(sx-x,sz-z)<1))continue;if(i%3===0)flower(island,x,z,i%2?'#fff4d2':'#eebea0',.65+rand(i+30)*.4);else{const rock=ball(island,i%5===0?'#c9cead':this.level.theme==='snow'?'#e5eee0':'#b5c78f',x,.1,z,.1+rand(i+40)*.18,.1,.18);rock.rotation.y=i}}
 for(const [x,z] of [[-9,-1.5],[-4,5.2],[7,2.6]]){ball(island,'#a5b980',x,.21,z,.45,.24,.37);ball(island,'#b6c791',x+.3,.2,z+.1,.3,.22,.3)}
 if(this.level.theme==='grove'){for(const [x,z] of [[-8,4],[-7,4.5],[7,-4],[-2,-5]]){const deco=towerModel('mushroom');deco.position.set(x,0,z);deco.scale.setScalar(.5);island.add(deco)}}
 const end=this.path.at(-1);cottage(island,end.x+.3,end.z);const start=this.path[0];cylinder(island,'#aa9068',start.x+.35,.65,start.z-.85,.045,.045,1.3,8);const flag=mesh(new THREE.BoxGeometry(.7,.4,.035),'#d18c6c',island,start.x+.69,1.09,start.z-.85);flag.rotation.y=.2;
 // Two complimentary guardians make the first battlefield immediately playable.
 this.addTower('pea',1,true);this.addTower('mushroom',5,true);this.setView('3d',false);this.emit();
 }
 towerAt(spot){return this.towers.find(t=>(t.occupiedSpots||[t.spot]).includes(spot))}
 addTower(type,spot,free=false){if(!TOWERS[type]||TOWERS[type].fusionOnly||!this.level.spots[spot]||this.towerAt(spot)||(!free&&!this.unlockedTowers.includes(type)))return false;if(!free&&(this.gold<TOWERS[type].cost||this.towerAt(spot)))return false;const [x,z]=this.level.spots[spot];const model=towerModel(type);model.position.set(x,.18,z);model.rotation.y=.3;this.dynamic.add(model);const tower={type,spot,occupiedSpots:[spot],model,level:1,cooldown:0,spent:TOWERS[type].cost};this.towers.push(tower);if(!free){this.gold-=TOWERS[type].cost;this.sound.play('build');this.burst(new THREE.Vector3(x,.5,z),'#f7dda0',18);this.shockwave(new THREE.Vector3(x,.2,z),'#ffe3a1',1.1);this.events.toast?.(`${TOWERS[type].name}準備好了！`)}return tower}
 move(event){if(!this.level)return;const r=this.canvas.getBoundingClientRect();this.pointer.set((event.clientX-r.left)/r.width*2-1,-((event.clientY-r.top)/r.height)*2+1);this.ray.setFromCamera(this.pointer,this.camera);if(!this.ray.ray.intersectPlane(this.plane,this.point))return;this.hover=this.level.spots.findIndex(([x,z])=>Math.hypot(x-this.point.x,z-this.point.z)<.9);this.updatePreview()}
 updatePreview(){if(!this.level)return;const occupied=this.towerAt(this.hover);for(let i=0;i<this.pads.length;i++){const reserved=occupied?.type==='super'&&(occupied.occupiedSpots||[]).includes(i);this.pads[i].scale.setScalar(i===this.hover?1.07:reserved?1.18:1)}if(this.ghost)this.ghost.visible=false;if(this.selectedType&&this.hover>=0&&!occupied){const [x,z]=this.level.spots[this.hover];if(this.ghost){this.ghost.visible=true;this.ghost.position.set(x,.18,z)}this.showRange(x,z,TOWERS[this.selectedType].range);this.canvas.style.cursor='crosshair'}else if(this.selectedTower){this.showRange(this.selectedTower.model.position.x,this.selectedTower.model.position.z,this.towerStats(this.selectedTower).range)}else{this.range.visible=false;this.rangeFill.visible=false;this.canvas.style.cursor=occupied||this.hover>=0?'pointer':this.selectedType?'crosshair':'grab'}}
 showRange(x,z,r){this.range.visible=true;this.rangeFill.visible=true;this.range.position.set(x,.19,z);this.rangeFill.position.set(x,.185,z);this.range.scale.setScalar(r);this.rangeFill.scale.setScalar(r)}
 select(type,emit=true){if(type&&(!this.unlockedTowers.includes(type)||TOWERS[type]?.fusionOnly)){this.events.toast?.('通關解鎖新章節後，就能永久使用這位守衛！');return}this.selectedType=type;this.selectedTower=null;if(this.ghost){this.scene.remove(this.ghost);this.ghost.traverse(o=>{if(o.material)o.material.dispose()});disposeGroup(this.ghost);this.ghost=null}if(type){this.ghost=towerModel(type);this.ghost.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.55;o.castShadow=false}});this.ghost.visible=false;this.scene.add(this.ghost)}this.canvas.classList.toggle('placing',!!type);this.updatePreview();if(emit)this.emit()}
 click(){if(this.finished||this.paused)return;if(this.hover<0){if(this.selectedTower){this.selectedTower=null;this.emit();this.updatePreview()}return}const tower=this.towerAt(this.hover);if(tower){this.select(null,false);this.selectedTower=tower;this.sound.play('click');this.updatePreview();this.emit()}else if(this.selectedType){if(this.gold<TOWERS[this.selectedType].cost){this.events.toast?.('陽光幣不足，再擊退一些小怪吧！');return}this.addTower(this.selectedType,this.hover);this.select(null)}else this.events.toast?.('先從右方挑選一位守衛，再點擊這裡種下！')}
 towerStats(tower){const data=TOWERS[tower.type];return {...data,damage:Math.round(data.damage*(1+(tower.level-1)*.65)),range:data.range+(tower.level-1)*.45,interval:data.interval/(1+(tower.level-1)*.12)}}
 upgrade(){const t=this.selectedTower;if(!t||t.type==='super'||t.level>=3||this.finished)return;const cost=Math.round(TOWERS[t.type].cost*.75*t.level);if(this.gold<cost){this.events.toast?.('陽光幣不足，先讓守衛再努力一下！');return}this.gold-=cost;t.spent+=cost;t.level++;const old=t.model;const model=towerModel(t.type,t.level);if(t.fusionMarker)model.add(t.fusionMarker);model.position.copy(old.position);model.rotation.copy(old.rotation);this.dynamic.remove(old);disposeGroup(old);this.dynamic.add(model);t.model=model;this.sound.play('build');this.burst(model.position.clone().add(new THREE.Vector3(0,1,0)),'#ffdf87',24);this.shockwave(model.position,'#ffdf87',1.5);this.updatePreview();this.emit()}
 sell(){const t=this.selectedTower;if(!t||t.type==='super'||this.finished)return;this.gold+=Math.floor(t.spent*.65);this.unmarkFusion(t);this.dynamic.remove(t.model);disposeGroup(t.model);this.towers.splice(this.towers.indexOf(t),1);this.selectedTower=null;this.sound.play('coin');this.updatePreview();this.emit()}
 toggleFusion(){const t=this.selectedTower;if(this.paused||!t||t.type==='super'||this.finished)return;const index=this.fusionSelected.indexOf(t);if(index>=0){this.unmarkFusion(t);this.events.toast?.(`已取消祭品 · ${this.fusionSelected.length} / 3`)}else{this.fusionSelected.push(t);const marker=mesh(new THREE.TorusGeometry(.86,.075,8,40),'#ffd968',t.model,0,2.45,0);marker.rotation.x=Math.PI/2;marker.material=marker.material.clone();marker.material.emissive=new THREE.Color('#ff9f32');marker.material.emissiveIntensity=1.8;t.fusionMarker=marker;this.sound.play('build');this.events.toast?.(`聚能祭品已選擇 · ${this.fusionSelected.length} / 3`)}if(this.fusionSelected.length===3)this.fuse();else this.emit()}
 unmarkFusion(t){const i=this.fusionSelected.indexOf(t);if(i>=0)this.fusionSelected.splice(i,1);if(t?.fusionMarker){t.model.remove(t.fusionMarker);t.fusionMarker.geometry.dispose();t.fusionMarker.material.dispose();t.fusionMarker=null}}
 fuse(){const chosen=[...this.fusionSelected];if(this.paused||this.finished||chosen.length!==3||chosen.some(t=>!this.towers.includes(t)||t.type==='super'))return;const center=chosen.reduce((v,t)=>v.add(t.model.position),new THREE.Vector3()).multiplyScalar(1/3);const anchor=chosen.reduce((best,t)=>t.model.position.distanceToSquared(center)<best.model.position.distanceToSquared(center)?t:best,chosen[0]);const occupied=chosen.flatMap(t=>t.occupiedSpots||[t.spot]);const target=anchor.model.position.clone();for(const t of chosen){const from=t.model.position.clone().add(new THREE.Vector3(0,1.5,0));this.fusionBeam(from,target.clone().add(new THREE.Vector3(0,1.8,0)));this.dynamic.remove(t.model);disposeGroup(t.model);this.towers.splice(this.towers.indexOf(t),1)}this.fusionSelected=[];const model=towerModel('super');model.position.copy(target);model.rotation.y=.3;model.scale.setScalar(.04);this.dynamic.add(model);const tower={type:'super',spot:anchor.spot,occupiedSpots:occupied,model,level:1,cooldown:0,spent:0,fusing:1.25};this.towers.push(tower);for(const spot of occupied){const [x,z]=this.level.spots[spot];const seal=mesh(new THREE.TorusGeometry(.57,.09,8,32),'#e7a538',this.dynamic,x,.28,z);seal.rotation.x=-Math.PI/2;}this.selectedTower=tower;this.burst(target.clone().add(new THREE.Vector3(0,1.5,0)),'#ffe36e',55);this.shockwave(target,'#ffd24f',3.2);this.shockwave(target,'#fff2a6',2.2,.18);this.sound.play('start');this.events.banner?.('三位守衛融合——太陽核巨砲誕生！');this.events.toast?.('超級砲台已佔據三個種植位置');this.updatePreview();this.emit()}
 fusionBeam(from,to){const geo=new THREE.BufferGeometry().setFromPoints([from,to]);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:'#fff09a',transparent:true,opacity:1}));this.dynamic.add(line);this.effects.push({model:line,life:1,total:1,kind:'fade'})}
 startWave(){if(this.active||this.finished||this.paused)return;this.select(null,false);this.wave++;this.queue=waveRoster(this.levelIndex,this.wave);this.spawnTimer=.25;this.active=true;this.sound.play('start');this.events.banner?.(`第 ${this.wave} 波 · ${this.wave===this.level.waves?'大魔王來搗蛋了！':'小怪來啦！'}`);this.emit()}
 spawn(spec){const model=enemyModel(spec.kind);model.traverse(o=>{if(o.isMesh&&o.material?.isMeshStandardMaterial)o.material=o.material.clone()});this.dynamic.add(model);const species=ENEMIES[spec.kind]||ENEMIES.normal;const hp=spec.hp*species.hp;const e={...spec,hp,maxHp:hp,speed:spec.speed*species.speed,armor:species.armor||0,shield:hp*(species.shield||0),burn:0,poison:0,stun:0,regenTimer:0,distance:0,slow:0,model,dead:false,phase:Math.random()*Math.PI*2,hitFlash:0};const bar=new THREE.Group();const bg=new THREE.Mesh(new THREE.PlaneGeometry(.72,.09),new THREE.MeshBasicMaterial({color:'#7c896c',depthTest:false}));const fg=new THREE.Mesh(new THREE.PlaneGeometry(.68,.055),new THREE.MeshBasicMaterial({color:'#aee57f',depthTest:false}));fg.position.z=.002;bar.add(bg,fg);bar.position.y=spec.kind==='boss'?2.05:1.3;model.add(bar);e.bar=bar;e.barFill=fg;const slowFx=new THREE.Group();slowFx.visible=false;const aura=mesh(new THREE.TorusGeometry(.52,.055,8,32),'#8eefff',slowFx,0,.18,0);aura.rotation.x=Math.PI/2;aura.material=aura.material.clone();aura.material.transparent=true;aura.material.opacity=.8;for(let i=0;i<5;i++){const a=i*Math.PI*2/5;const ice=mesh(new THREE.OctahedronGeometry(.13),'#c8ffff',slowFx,Math.sin(a)*.53,.55,Math.cos(a)*.53);ice.scale.y=1.7}model.add(slowFx);e.slowFx=slowFx;e.bodyBase=model.userData.body.scale.clone();this.enemies.push(e);this.moveEnemy(e,0)}
 moveEnemy(e,dt){e.slow=Math.max(0,e.slow-dt);e.stun=Math.max(0,e.stun-dt);e.burn=Math.max(0,e.burn-dt);e.poison=Math.max(0,e.poison-dt);
 if(e.burn>0||e.poison>0)this.damage(e,dt*((e.burn>0?15:0)+(e.poison>0?12:0)),'dot');
 if(e.dead)return;
 if(e.kind==='healer'&&e.burn<=0){e.regenTimer+=dt;if(e.regenTimer>=2){e.regenTimer=0;for(const ally of this.enemies)if(!ally.dead&&ally.model.position.distanceTo(e.model.position)<2.5)ally.hp=Math.min(ally.maxHp,ally.hp+ally.maxHp*.06);this.shockwave(e.model.position,'#a9ffb0',2.5)}}
 e.distance+=dt*e.speed*(e.stun>0?0:e.slow>0?(ENEMIES[e.kind]?.resistSlow?.85:.45):1);const s=this.segments.find(s=>e.distance<=s.start+s.length)||this.segments.at(-1);const p=s.a.clone().lerp(s.b,Math.min(1,(e.distance-s.start)/s.length));e.model.position.copy(p);e.model.position.y+=Math.abs(Math.sin(this.time*(e.slow>0?3:8)+e.phase))*.1;e.model.rotation.y=Math.atan2(s.b.x-s.a.x,s.b.z-s.a.z);e.bar.quaternion.copy(this.camera.quaternion);e.bar.rotateY(-e.model.rotation.y);e.barFill.scale.x=Math.max(0,e.hp/e.maxHp);e.barFill.position.x=-(1-e.hp/e.maxHp)*.34;if(e.model.userData.shield)e.model.userData.shield.visible=e.shield>0;e.slowFx.visible=e.slow>0||e.burn>0||e.poison>0||e.stun>0;const statusColor=e.stun>0?'#e6a4ff':e.burn>0?'#ff732e':e.poison>0?'#91eb48':'#8eefff';e.slowFx.children[0].material.color.set(statusColor);if(e.slowFx.visible){e.slowFx.rotation.y-=dt*(e.stun>0?8:4);e.slowFx.scale.setScalar(1+Math.sin(this.time*7)*.12)}if(e.distance>=this.totalLength-.55){e.dead=true;this.hp=Math.max(0,this.hp-(e.kind==='boss'?4:1));this.sound.play('hurt');this.shockwave(e.model.position,'#df8b76',1.3);this.emit();if(this.hp<=0)this.end(false)}}
 fire(t,e){if(t.fusing>0)return;const stats=this.towerStats(t),height=t.type==='super'?3.05:1.4,p=t.model.position.clone().add(new THREE.Vector3(0,height,0));const color=TOWERS[t.type].color;let obj;if(t.type==='super'){obj=new THREE.Group();const core=ball(obj,'#fff3a3',0,0,0,.5);const ring=mesh(new THREE.TorusGeometry(.66,.1,10,30),'#ff9f32',obj);ring.rotation.x=Math.PI/2;const light=new THREE.PointLight('#ffd45f',1.5,4);obj.add(light);this.dynamic.add(obj)}else obj=t.type==='frost'?mesh(new THREE.OctahedronGeometry(.22),color,this.dynamic):ball(this.dynamic,color,0,0,0,t.type==='mushroom'?.28:.18);if(['lightning','flame','venom','nova'].includes(t.type)){
 const halo=mesh(new THREE.TorusGeometry(t.type==='nova'?.42:.28,.045,8,24),color,obj);halo.rotation.x=Math.PI/2;
 obj.scale.setScalar(t.type==='nova'?.42:.28);
 // Ball geometry uses unit radius; keep orbit details at matching local scale.
 halo.scale.setScalar(3);
 if(t.type==='lightning')this.arc(p,e.model.position,color);
 }obj.position.copy(p);this.shots.push({model:obj,target:e,start:p,age:0,duration:t.type==='mushroom'?.48:t.type==='super'?.18:.23,type:t.type,damage:stats.damage});t.cooldown=stats.interval;this.sound.play(['super','flame','nova'].includes(t.type)?'mushroom':['venom','lightning'].includes(t.type)?'frost':t.type);t.recoil=t.type==='super'?.2:.12}
 hit(shot){
 const target=shot.target,pos=shot.model.position,color=TOWERS[shot.type].color;
 if(shot.type==='lightning'){
  let current=target;const visited=new Set();
  for(let i=0;i<4&&current;i++){visited.add(current);if(!current.dead)this.damage(current,shot.damage*Math.pow(.8,i),'lightning');const next=this.enemies.filter(e=>!e.dead&&!visited.has(e)&&e.model.position.distanceTo(current.model.position)<3).sort((a,b)=>a.model.position.distanceTo(current.model.position)-b.model.position.distanceTo(current.model.position))[0];if(next)this.arc(current.model.position,next.model.position,color);current=next}
  this.shockwave(pos,color,1);return;
 }
 const radius={mushroom:1.8,super:1.65,flame:1.6,venom:1.5,nova:2.3}[shot.type];
 const victims=radius?this.enemies.filter(e=>!e.dead&&e.model.position.distanceTo(pos)<radius):target.dead?[]:[target];
 for(const e of victims){if(shot.type==='frost')e.slow=3.2;if(shot.type==='flame')e.burn=3;if(shot.type==='venom')e.poison=4;if(shot.type==='nova')e.stun=e.kind==='boss'?.25:.7;this.damage(e,shot.damage,shot.type)}
 this.burst(pos,color,shot.type==='super'?12:radius?18:8);
 if(radius)this.shockwave(pos,color,radius);
 if(shot.type==='nova'){this.shockwave(pos,'#fff3ff',2.7,.1);this.arc(pos.clone().add(new THREE.Vector3(0,5,0)),pos,color)}
 }
 arc(from,to,color){const a=from.clone().add(new THREE.Vector3(0,.6,0)),b=to.clone().add(new THREE.Vector3(0,.6,0));const points=[a];for(let i=1;i<6;i++)points.push(a.clone().lerp(b,i/6).add(new THREE.Vector3((Math.random()-.5)*.5,(Math.random()-.5)*.5,(Math.random()-.5)*.5)));points.push(b);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color,transparent:true,opacity:1}));this.dynamic.add(line);this.effects.push({model:line,life:.3,total:.3,kind:'fade'})}

 damage(e,value,kind='pea'){if(e.dead)return;const bypass=['lightning','dot','venom'].includes(kind);if(!bypass&&e.poison<=0)value*=1-e.armor;if(e.shield>0){const absorbed=Math.min(e.shield,value);e.shield-=absorbed;value-=absorbed;}e.hp-=value;e.hitFlash=kind==='dot'?0:.22;e.hitKind=kind;const body=e.model.userData.body;if(body.material?.emissive){body.material.emissive.set(kind==='frost'?'#71e8ff':kind==='mushroom'?'#ff743b':kind==='super'?'#fff09a':'#a7e96c');body.material.emissiveIntensity=2.4}if(e.hp<=0&&!e.dead){e.dead=true;this.kills++;this.gold+=e.kind==='boss'?65:e.kind==='fast'?9:12;if(e.kind==='swarm'){for(let i=0;i<2;i++){this.spawn({kind:'fast',hp:e.maxHp*.18,speed:e.speed});const child=this.enemies.at(-1);child.distance=e.distance+i*.3;this.moveEnemy(child,0)}}this.sound.play('coin');this.burst(e.model.position.clone().add(new THREE.Vector3(0,.4,0)),'#f5d279',16);this.shockwave(e.model.position,'#f5d279',1.25);this.emit()}}
 burst(pos,color,count){for(let i=0;i<count&&this.particles.length<260;i++){const size=.07+Math.random()*.09,m=ball(this.dynamic,color,pos.x,pos.y,pos.z,size);const life=.45+Math.random()*.4;this.particles.push({model:m,baseScale:m.scale.clone(),velocity:new THREE.Vector3((Math.random()-.5)*4,1+Math.random()*3,(Math.random()-.5)*4),life,total:life})}}
 shockwave(pos,color,size,delay=0){const ring=new THREE.Mesh(new THREE.RingGeometry(.72,1,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(pos);ring.position.y=.3;ring.scale.setScalar(.1);this.dynamic.add(ring);this.effects.push({model:ring,life:.55,total:.55,size,delay,kind:'ring'})}
 removeDynamic(obj){this.dynamic.remove(obj);obj.traverse(o=>{if(o.material&&!Array.isArray(o.material)&&o.material.isMeshBasicMaterial)o.material.dispose()});disposeGroup(obj)}
 tick(dt){if(!this.level||this.paused||this.finished)return;this.time+=dt;for(const t of this.towers){t.model.userData.head.position.y=Math.sin(this.time*(t.type==='super'?4:2)+t.spot)*.035;if(t.model.userData.halo)t.model.userData.halo.rotation.z+=dt*2.8;if(t.fusing>0){t.fusing=Math.max(0,t.fusing-dt);const p=1-t.fusing/1.25,ease=1-Math.pow(1-p,3),bounce=1+Math.sin(p*Math.PI*3)*.18*(1-p);t.model.scale.setScalar(1.55*ease*bounce)}if(t.recoil>0){t.recoil-=dt;t.model.userData.head.scale.setScalar(1+Math.max(0,t.recoil)*(t.type==='super'?1.2:.3))}else t.model.userData.head.scale.setScalar(1)}
 for(const e of this.enemies){if(e.dead)continue;e.hitFlash=Math.max(0,e.hitFlash-dt);const body=e.model.userData.body;if(e.hitFlash>0){const pulse=1+Math.sin(e.hitFlash*55)*.22;body.scale.copy(e.bodyBase).multiplyScalar(pulse)}else{body.scale.copy(e.bodyBase);if(body.material?.emissive){body.material.emissive.set(e.stun>0?'#db83ff':e.burn>0?'#ff6418':e.poison>0?'#83fa36':e.slow>0?'#59ddeb':'#000000');body.material.emissiveIntensity=e.stun>0||e.burn>0||e.poison>0?1.2:e.slow>0?.75:0}}}
 if(this.active){this.spawnTimer-=dt;if(this.queue.length&&this.spawnTimer<=0){this.spawn(this.queue.shift());this.spawnTimer=Math.max(.48,1.6-this.wave*.08-this.levelIndex*.1)}for(const e of this.enemies){if(!e.dead)this.moveEnemy(e,dt);if(this.finished)break}if(this.finished)return;
 for(const t of this.towers){if(t.fusing>0)continue;t.cooldown-=dt;const stats=this.towerStats(t);const target=this.enemies.filter(e=>!e.dead&&e.model.position.distanceTo(t.model.position)<stats.range).sort((a,b)=>b.distance-a.distance)[0];if(target){const delta=target.model.position.clone().sub(t.model.position);const desired=Math.atan2(delta.x,delta.z);const diff=Math.atan2(Math.sin(desired-t.model.rotation.y),Math.cos(desired-t.model.rotation.y));t.model.rotation.y+=diff*Math.min(1,dt*12);if(t.cooldown<=0)this.fire(t,target)}}}
 for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];s.age+=dt;const k=Math.min(1,s.age/s.duration);s.model.position.copy(s.start).lerp(s.target.model.position.clone().add(new THREE.Vector3(0,s.type==='super'?.8:.5,0)),k);if(['mushroom','flame','venom','nova'].includes(s.type))s.model.position.y+=Math.sin(k*Math.PI)*2;if(s.type==='super'){const pulse=1+Math.sin(k*Math.PI*5)*.16;s.model.scale.setScalar(pulse)}s.model.rotation.y+=dt*(s.type==='super'?18:5);if(k>=1){this.hit(s);this.removeDynamic(s.model);this.shots.splice(i,1)}}
 for(let i=this.enemies.length-1;i>=0;i--){if(this.enemies[i].dead){this.removeDynamic(this.enemies[i].model);this.enemies.splice(i,1)}}
 for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.life-=dt;p.velocity.y-=dt*6;p.model.position.addScaledVector(p.velocity,dt);p.model.scale.copy(p.baseScale).multiplyScalar(Math.max(0,p.life/p.total));if(p.life<=0){this.removeDynamic(p.model);this.particles.splice(i,1)}}
 for(let i=this.effects.length-1;i>=0;i--){const fx=this.effects[i];if(fx.delay>0){fx.delay-=dt;continue}fx.life-=dt;const p=1-Math.max(0,fx.life)/fx.total;if(fx.kind==='ring'){fx.model.scale.setScalar(.1+fx.size*p);fx.model.material.opacity=(1-p)*.9}else if(fx.kind==='fade')fx.model.material.opacity=Math.max(0,fx.life/fx.total);if(fx.life<=0){this.dynamic.remove(fx.model);fx.model.traverse?.(o=>{o.geometry?.dispose();o.material?.dispose()});this.effects.splice(i,1)}}
 if(this.active&&!this.queue.length&&!this.enemies.length&&!this.shots.length){this.active=false;this.gold+=this.level.reward;if(this.wave>=this.level.waves)this.end(true);else{this.sound.play('build');this.events.banner?.(`守住了！ +${this.level.reward} 陽光幣`);this.emit()}}
 }
 end(won){if(this.finished)return;this.finished=true;this.active=false;this.select(null,false);this.sound.play(won?'win':'lose');this.emit();this.events.end?.({won,level:this.levelIndex,hp:this.hp,kills:this.kills,stars:this.hp>=18?3:this.hp>=10?2:1})}
 togglePause(){if(this.finished)return;this.paused=!this.paused;this.emit()}
 toggleSpeed(){this.speed=this.speed===1?2:1;this.emit()}
 setView(view,animate=true){this.view=view;const target=view==='2d'?new THREE.Vector3(0,34,.01):new THREE.Vector3(17,21,25);this.controls.enableRotate=view!=='2d';if(animate)this.cameraTween={from:this.camera.position.clone(),to:target,t:0};else{this.camera.position.copy(target);this.camera.zoom=1;this.camera.updateProjectionMatrix();this.controls.update()}this.events.view?.(view)}
 zoom(delta){this.camera.zoom=THREE.MathUtils.clamp(this.camera.zoom+delta,.7,1.8);this.camera.updateProjectionMatrix()}
 loop(now){this.frame=requestAnimationFrame(this.loop);const dt=Math.min((now-this.last)/1000,.06);this.last=now;if(this.cameraTween){this.cameraTween.t=Math.min(1,this.cameraTween.t+dt*2.5);const t=this.cameraTween.t;this.camera.position.lerpVectors(this.cameraTween.from,this.cameraTween.to,t*t*(3-2*t));if(t>=1)this.cameraTween=null}this.controls.update();this.tick(dt*this.speed);this.renderer.render(this.scene,this.camera)}
}
