import './style.css';
import { createIcons, Sprout, LayoutGrid, Map, BookOpen, Trophy, Settings2, CircleHelp, Volume2, VolumeX, Heart, Coins, Flag, Leaf, Box, Layers2, MousePointer2, RotateCcw, Plus, Minus, Pause, Play, FastForward, Swords, Crosshair, Zap, Snowflake, Sparkles, ChevronRight, Check, X, ShieldCheck, Cloud, Keyboard, Target, ArrowUp, CircleCheck, Sun } from 'lucide';
import { Game } from './game.js';
import { makePreviews } from './models.js';
import { Sound } from './audio.js';
import { LEVELS,TOWERS } from './data.js';
const icons={Sprout,LayoutGrid,Map,BookOpen,Trophy,Settings2,CircleHelp,Volume2,VolumeX,Heart,Coins,Flag,Leaf,Box,Layers2,MousePointer2,RotateCcw,Plus,Minus,Pause,Play,FastForward,Swords,Crosshair,Zap,Snowflake,Sparkles,ChevronRight,Check,X,ShieldCheck,Cloud,Keyboard,Target,ArrowUp,CircleCheck,Sun};
const icon=(name,extra='')=>`<i data-lucide="${name}" ${extra}></i>`;
const refreshIcons=()=>createIcons({icons,attrs:{'aria-hidden':'true'}});
let saved={stars:[0,0,0],muted:false};
try{const s=JSON.parse(localStorage.getItem('sprout-guardians')||'null');if(s&&Array.isArray(s.stars))saved={...saved,...s,stars:s.stars.slice(0,3)}}catch{}
function persist(){try{localStorage.setItem('sprout-guardians',JSON.stringify(saved))}catch{}}
function miniMap(i){const colors=[['#dbe5c3','#8eae71','#eee1b9'],['#e8ddbb','#aba76b','#f6e9cb'],['#d6e6dd','#93bdb0','#eff4e9']][i];const points=LEVELS[i].path.map(([x,z])=>`${(x+11)*4.5},${(z+6)*5}`).join(' ');return `<svg viewBox="0 0 100 60" fill="none"><rect width="100" height="60" fill="${colors[0]}"/><path d="M${points.replaceAll(' ',' L')}" stroke="${colors[2]}" stroke-width="8" stroke-linecap="round" stroke-linejoin="round"/><ellipse cx="18" cy="13" rx="8" ry="9" fill="${colors[1]}"/><ellipse cx="79" cy="45" rx="9" ry="10" fill="${colors[1]}"/><circle cx="46" cy="13" r="4" fill="${colors[1]}"/><rect x="87" y="25" width="9" height="10" rx="2" fill="#fff2d3"/><path d="m85 27 7-7 7 7" fill="#c68c6d"/></svg>`}
document.querySelector('#app').innerHTML=`
<div class="shell">
 <aside class="rail" aria-label="主選單">
  <div class="brand" title="萌芽守衛隊">${icon('sprout')}</div>
  <nav class="rail-nav">
   <button class="rail-button active" id="nav-play" aria-label="遊戲花園" title="遊戲花園">${icon('layout-grid')}</button>
   <button class="rail-button" id="nav-maps" aria-label="關卡地圖" title="關卡地圖">${icon('map')}</button>
   <button class="rail-button" id="nav-collection" aria-label="守衛圖鑑" title="守衛圖鑑">${icon('book-open')}</button>
   <button class="rail-button" id="nav-achievements" aria-label="冒險成就" title="冒險成就">${icon('trophy')}</button>
  </nav>
  <div class="rail-bottom"><button class="rail-button" id="settings" aria-label="遊戲設定" title="遊戲設定">${icon('settings-2')}</button><div class="avatar" title="花園守護者">G</div></div>
 </aside>
 <main class="main">
  <header class="topbar">
   <div><p class="eyebrow">SMALL GUARDIANS. BIG ADVENTURES.</p><div class="title"><h1>萌芽守衛隊</h1><span class="tag">3D 塔防</span></div><p class="subtitle">種下小小守衛，守護大大花園。</p></div>
   <div class="top-right"><span class="saved">${icon('cloud')} 冒險進度自動保存</span><button class="icon-btn" id="sound" aria-label="關閉音效" title="開關音效">${icon('volume-2')}</button><button class="icon-btn" id="help" aria-label="遊戲教學" title="遊戲教學">${icon('circle-help')}</button></div>
  </header>
  <div class="workspace">
   <section class="game-section" aria-label="塔防遊戲">
    <div class="game-top"><div class="current-label"><span class="status-dot"></span><strong id="current-level">01 · 微風草原</strong><span id="phase">準備階段</span></div><div class="stats"><div class="stat gold" title="陽光幣">${icon('coins')}<span id="gold">2400</span></div><div class="stat life" title="花園生命">${icon('heart')}<span id="hp">20</span></div><div class="stat wave" title="目前波次">${icon('flag')}<span id="wave">0 <small>/ 5</small></span></div></div></div>
    <div class="viewport">
     <canvas id="scene" aria-label="3D 花園戰場，選取守衛後點擊圓形種植台建造；拖曳旋轉視角" tabindex="0"></canvas>
     <div class="map-badge">${icon('leaf')}<span id="map-badge-text">微風草原</span><span style="opacity:.4">/</span><span id="map-difficulty">入門</span></div>
     <div class="view-toggle" aria-label="視角切換"><button id="view-3d" class="selected" aria-pressed="true">${icon('box')}3D</button><button id="view-2d" aria-pressed="false">${icon('layers-2')}俯視</button></div>
     <div class="map-coordinate">THE LITTLE GARDEN · 01</div>
     <div class="map-instruction">${icon('mouse-pointer-2')}<span id="instruction">選擇守衛，點擊空地開始種植</span></div>
     <div class="camera-tools"><button id="reset-camera" aria-label="重設視角" title="重設視角">${icon('rotate-ccw')}</button><button id="zoom-out" aria-label="縮小視角">${icon('minus')}</button><button id="zoom-in" aria-label="放大視角">${icon('plus')}</button></div>
     <div class="wave-banner" aria-live="polite"><span></span></div>
     <div id="tower-detail" class="tower-detail" hidden></div>
     <button class="paused-cover" id="paused-cover" hidden>${icon('pause')}花園休息中<small>點擊繼續守護花園</small></button>
    </div>
    <div class="game-controls"><div class="control-left"><button class="icon-btn" id="pause" aria-label="暫停遊戲" title="暫停 / 繼續（空白鍵）">${icon('pause')}</button><button class="speed-button" id="speed" aria-label="切換為兩倍速度">${icon('fast-forward')}<span>1×</span></button><button class="icon-btn" id="restart" aria-label="重新開始關卡" title="重新開始">${icon('rotate-ccw')}</button><span><kbd>Space</kbd>暫停遊戲</span></div><button class="start-wave" id="start-wave">${icon('play')}<span>開始第一波</span><kbd>Enter</kbd></button></div>
    <section class="level-section" id="level-section"><div class="section-heading"><h2>${icon('map')}花園冒險</h2><span id="completed-count">3 個小世界，等你來守護</span></div><div class="levels">${LEVELS.map((l,i)=>`<button class="level-card ${i===0?'active':''}" data-level="${i}" aria-label="選擇第 ${i+1} 關：${l.name}" aria-pressed="${i===0}"><div class="level-art">${miniMap(i)}</div><div class="level-copy"><small>CHAPTER 0${i+1}</small><strong>${l.name}</strong><div class="difficulty" aria-label="難度 ${i+1}">${[0,1,2].map(n=>`<i class="${n<=i?'on':''}"></i>`).join('')}</div></div><span class="level-check" ${i!==0?'hidden':''}>${icon('check')}</span></button>`).join('')}</div></section>
   </section>
   <aside class="sidebar" aria-label="守衛選擇"><div class="sidebar-top"><div class="sidebar-title">${icon('sprout')}<h2>選一位小小守衛</h2></div><p>每一顆萌芽，都有自己的超能力。</p></div><div class="tower-list">${Object.entries(TOWERS).filter(([,t])=>!t.fusionOnly).map(([key,t],i)=>`<button class="tower-card" data-tower="${key}" aria-label="選擇${t.name}，${t.cost} 陽光幣" aria-pressed="false"><span class="tower-shortcut">${i+1}</span><div class="tower-top"><img class="tower-image" data-preview="${key}" alt="${t.name}立體模型"/><div class="tower-info"><h3>${t.name}</h3><span class="tower-type">${t.tag}</span><div class="price">${icon('coins')}${t.cost}</div></div></div><div class="tower-bottom"><span>${icon(key==='frost'?'snowflake':'swords')}${key==='frost'?'緩速':'傷害'} <b>${key==='frost'?'55%':t.damage}</b></span><span>${icon('crosshair')}射程 <b>${t.range.toFixed(1)}</b></span><span>${icon('zap')}<b>${key==='pea'?'快速':key==='mushroom'?'範圍':'控場'}</b></span></div></button>`).join('')}</div><div class="tip-card"><div class="tip-heading">${icon('sparkles')}花園小筆記</div><p id="tip">把守衛種在轉彎處，可以多陪小怪走一段路，也能多攻擊幾次喔。</p></div></aside>
  </div>
  <footer class="footer"><span>${icon('sprout')}用一點策略，換一整座花園的平靜。</span><span>拖曳旋轉 · 滾輪縮放 · 1 / 2 / 3 選擇守衛 · Esc 取消</span><span>MADE FOR LITTLE MOMENTS</span></footer>
 </main>
</div><div class="toast" role="status" aria-live="polite"></div><div class="modal-overlay" id="modal-overlay" hidden><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" id="modal"></section></div>`;
refreshIcons();
const $=s=>document.querySelector(s);const sound=new Sound();sound.enabled=!saved.muted;let game;let previews={};let toastTimer,bannerTimer;let modalWasPaused=false,lastFocused;const overlay=$('#modal-overlay');
function toast(message){$('.toast').textContent=message;$('.toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.toast').classList.remove('visible'),2700)}
function banner(message){$('.wave-banner span').textContent=message;$('.wave-banner').classList.add('show');clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('.wave-banner').classList.remove('show'),2200)}
function update(g){$('#gold').textContent=g.gold;$('#hp').textContent=g.hp;$('#wave').innerHTML=`${g.wave} <small>/ ${g.level.waves}</small>`;$('#current-level').textContent=`0${g.levelIndex+1} · ${g.level.name}`;$('#phase').textContent=g.finished?'冒險結束':g.paused?'已暫停':g.active?'守護中':'準備階段';$('#map-badge-text').textContent=g.level.name;$('#map-difficulty').textContent=['入門','進階','挑戰'][g.levelIndex];$('.map-coordinate').textContent=`THE LITTLE GARDEN · 0${g.levelIndex+1}`;
 $('#start-wave').disabled=g.active||g.finished||g.paused;$('#start-wave span').textContent=g.finished?'冒險已結束':g.active?'守衛們努力中…':g.wave===0?'開始第一波':`開始第 ${g.wave+1} 波`;$('#pause').innerHTML=icon(g.paused?'play':'pause');$('#pause').setAttribute('aria-label',g.paused?'繼續遊戲':'暫停遊戲');$('#pause').disabled=g.finished;$('#paused-cover').hidden=!g.paused;$('#speed span').textContent=g.speed+'×';$('#speed').setAttribute('aria-label',`切換為${g.speed===1?'兩':'一'}倍速度`);
 $('[data-tower="pea"]').parentElement.querySelectorAll('.tower-card').forEach(b=>{const selected=b.dataset.tower===g.selectedType;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',selected);});document.querySelectorAll('.level-card').forEach((b,i)=>{b.classList.toggle('active',i===g.levelIndex);b.setAttribute('aria-pressed',i===g.levelIndex);b.querySelector('.level-check').hidden=i!==g.levelIndex});
 $('#instruction').textContent=g.selectedType?`點擊圓形空地種下${TOWERS[g.selectedType].name} · Esc 取消`:g.selectedTower?.type==='super'?'太陽核巨砲佔據三個位置，正在全速轟擊！':g.levelIndex===1&&g.selectedTower?'可將這座砲台選為融合祭品':g.active?'守衛出擊！你仍然可以種植或升級':'選擇守衛，點擊空地開始種植';
 const detail=$('#tower-detail'),t=g.selectedTower;detail.hidden=!t;if(t){const stats=g.towerStats(t),superTower=t.type==='super',cost=Math.round(TOWERS[t.type].cost*.75*t.level),marked=g.fusionSelected.includes(t);detail.classList.toggle('super-detail',superTower);detail.innerHTML=`<button class="detail-close" id="detail-close" aria-label="關閉守衛資訊">×</button><strong>${superTower?'✦ ':''}${TOWERS[t.type].name}${superTower?'':' · Lv.'+t.level}</strong><p>傷害 ${stats.damage}　射程 ${stats.range.toFixed(1)}　${stats.interval.toFixed(2)} 秒／發${superTower?'<br>巨型範圍砲彈 · 佔據 3 個位置':''}</p><div class="detail-actions">${superTower?'<span class="super-ready">太陽能量全開</span>':`<button id="upgrade" ${t.level>=3?'disabled':''}>${t.level>=3?'已達最高等級':`升級 · ${cost} 幣`}</button><button class="sell" id="sell">回收 · ${Math.floor(t.spent*.65)} 幣</button>${g.levelIndex===1?`<button class="fusion ${marked?'marked':''}" id="fusion">${marked?'取消祭品':`融合祭品 ${g.fusionSelected.length} / 3`}</button>`:''}`}</div>`;if(!superTower){$('#upgrade').onclick=()=>g.upgrade();$('#sell').onclick=()=>g.sell();if($('#fusion'))$('#fusion').onclick=()=>g.toggleFusion()}$('#detail-close').onclick=()=>g.select(null)}else detail.classList.remove('super-detail');
 refreshIcons();}
function openModal(content){lastFocused=document.activeElement;if(game){modalWasPaused=game.paused;if(!game.paused&&!game.finished){game.paused=true;game.emit()}}$('#modal').innerHTML=`<button class="icon-btn modal-close" id="close-modal" aria-label="關閉視窗">${icon('x')}</button>${content}`;overlay.hidden=false;$('#close-modal').onclick=closeModal;refreshIcons();$('#close-modal').focus()}
function closeModal(){overlay.hidden=true;if(game&&!game.finished){game.paused=modalWasPaused;game.emit()}lastFocused?.focus()}
function updateSound(){saved.muted=!sound.enabled;$('#sound').innerHTML=icon(sound.enabled?'volume-2':'volume-x');$('#sound').setAttribute('aria-label',sound.enabled?'關閉音效':'開啟音效');persist();refreshIcons()}
function help(){openModal(`<div class="modal-mark">${icon('sprout')}</div><p class="eyebrow">WELCOME, GARDEN KEEPER</p><h2 id="modal-title">小小花園，需要你。</h2><p>搗蛋小怪想溜進花園！種下可愛的守衛，一起保護終點的小屋。</p><div class="modal-row">${icon('mouse-pointer-2')}<span>選擇右側守衛，再點擊地圖上的圓形種植台。<br>已有兩位守衛免費加入你的隊伍。</span></div><div class="modal-row">${icon('sparkles')}<span>第二關限定：依序點選任意三座砲台，按下「融合祭品」。<br>第三座確認後，會自動融合成佔據三格的太陽核巨砲。</span></div><div class="modal-row">${icon('arrow-up')}<span>豌豆攻速快、蘑菇打範圍、冰晶花會讓怪物明顯結冰緩速。</span></div><div class="modal-row">${icon('keyboard')}<span>1 / 2 / 3 選擇守衛 · Enter 開始波次<br>空白鍵暫停 · Esc 取消 · 拖曳旋轉 · 滾輪縮放</span></div><button class="primary" id="help-go">一起守護花園</button>`);$('#help-go').onclick=closeModal}
function loadLevel(i){closeModal();game.load(i);$('#tip').textContent=['起始陽光幣已提升 10 倍，盡情測試各種配置吧！','融合實驗開放！點選任意三座砲台設為祭品，召喚太陽核巨砲。','最後一波有大魔王！冰晶花現在會讓牠明顯結冰並減速。'][i];banner(`第 ${i+1} 章 · ${LEVELS[i].name}`)}
function confirmReset(i){if(game.wave===0&&game.towers.length===2||game.finished){loadLevel(i);return}openModal(`<div class="modal-mark">${icon('rotate-ccw')}</div><h2 id="modal-title">${i===game.levelIndex?'重新整理這座花園？':'前往另一座花園？'}</h2><p>目前關卡的波次和種植配置將會重置，已獲得的通關星星會保留。</p><button class="primary" id="confirm-reset">${i===game.levelIndex?'重新開始':'前往'+LEVELS[i].name}</button><button class="secondary" id="cancel-reset">繼續守護這裡</button>`);$('#confirm-reset').onclick=()=>loadLevel(i);$('#cancel-reset').onclick=closeModal}
function finish(result){if(result.won){saved.stars[result.level]=Math.max(saved.stars[result.level]||0,result.stars);persist()}$('#completed-count').textContent=`已守護 ${saved.stars.filter(s=>s>0).length} / 3 座花園`;
 openModal(`<div class="modal-mark">${icon(result.won?'trophy':'heart')}</div><p class="eyebrow">${result.won?'A LITTLE VICTORY':'EVERY SPROUT STARTS SOMEWHERE'}</p><h2 id="modal-title">${result.won?'花園，守住了！':'再種下一次希望。'}</h2>${result.won?`<div class="modal-stars" aria-label="獲得 ${result.stars} 顆星">${'★'.repeat(result.stars)}${'☆'.repeat(3-result.stars)}</div>`:''}<p>${result.won?`${LEVELS[result.level].name}又恢復了平靜。謝謝你，花園守護者！`:'小怪們這次溜進了花園。試著在轉彎處種下更多守衛，並搭配緩速和範圍攻擊。'}</p><div class="modal-row">${icon('shield-check')}擊退 ${result.kills} 隻小怪　·　剩餘 ${result.hp} 點生命</div><button class="primary" id="result-next">${result.won&&result.level<2?'前往下一座花園':result.won?'再次守護這座花園':'再挑戰一次'}</button><button class="secondary" id="result-close">看看我的花園</button>`);$('#result-next').onclick=()=>loadLevel(result.won&&result.level<2?result.level+1:result.level);$('#result-close').onclick=closeModal;
}
try{previews=makePreviews();document.querySelectorAll('[data-preview]').forEach(img=>img.src=previews[img.dataset.preview]);game=new Game($('#scene'),sound,{update,toast,banner,end:finish,view(view){for(const v of ['3d','2d']){$('#view-'+v).classList.toggle('selected',v===view);$('#view-'+v).setAttribute('aria-pressed',v===view)}}});game.load(0)}catch(error){console.error(error);$('.viewport').insertAdjacentHTML('beforeend',`<div class="renderer-error"><h2>花園需要 WebGL 才能萌芽</h2><p>請使用支援 WebGL 的瀏覽器，並開啟硬體加速後重新整理。</p></div>`)}
updateSound();
$('#sound').onclick=()=>{sound.toggle();updateSound();toast(sound.enabled?'音效已開啟，聽聽花園的聲音':'音效已關閉')};$('#help').onclick=help;$('#nav-play').onclick=()=>{$('#scene').scrollIntoView({behavior:'smooth',block:'center'});$('#scene').focus({preventScroll:true})};$('#nav-maps').onclick=()=>{$('#level-section').scrollIntoView({behavior:'smooth',block:'center'});toast('三座花園已開放，選一張地圖就能開始冒險')};
$('#nav-collection').onclick=()=>{openModal(`<div class="modal-mark">${icon('book-open')}</div><p class="eyebrow">MEET YOUR LITTLE GUARDIANS</p><h2 id="modal-title">花園守衛圖鑑</h2><p>三種個性，無限可能。每位守衛都能升級至 Lv.3；第二關還藏著融合守衛。</p><div class="collection-grid">${Object.entries(TOWERS).filter(([,t])=>!t.fusionOnly).map(([k,t])=>`<div class="collection-item"><img src="${previews[k]||''}" alt="${t.name}"><strong>${t.name}</strong></div>`).join('')}</div>${Object.values(TOWERS).map(t=>`<p><b>${t.name}</b> · ${t.description}</p>`).join('')}`)};
$('#nav-achievements').onclick=()=>openModal(`<div class="modal-mark">${icon('trophy')}</div><p class="eyebrow">YOUR GARDEN STORY</p><h2 id="modal-title">每一顆星，都是守護。</h2><p>生命剩餘 18 點以上可獲得 3 星，10 點以上獲得 2 星。你的最佳紀錄會保存在這台裝置。</p>${LEVELS.map((l,i)=>`<div class="settings-row"><span>0${i+1} · ${l.name}</span><span style="color:#c5a55c;letter-spacing:4px">${'★'.repeat(saved.stars[i]||0)}${'☆'.repeat(3-(saved.stars[i]||0))}</span></div>`).join('')}`);
$('#settings').onclick=()=>{openModal(`<div class="modal-mark">${icon('settings-2')}</div><h2 id="modal-title">讓花園剛剛好。</h2><div class="settings-row"><span>遊戲音效</span><button class="setting-toggle" id="settings-sound">${sound.enabled?'已開啟':'已關閉'}</button></div><div class="settings-row"><label for="volume">音效音量</label><input id="volume" type="range" min="0" max="100" value="${Math.round(sound.volume*200)}" aria-label="音效音量" style="accent-color:#64854f;width:145px"></div><p>進度會自動儲存在此瀏覽器。<br>提示：使用耳機，可以聽見每種守衛不同的攻擊聲。</p>`);$('#settings-sound').onclick=()=>{sound.toggle();updateSound();$('#settings-sound').textContent=sound.enabled?'已開啟':'已關閉'};$('#volume').oninput=e=>{sound.unlock();sound.volume=Number(e.target.value)/200;sound.play('click')}};
if(game){document.querySelectorAll('[data-tower]').forEach(b=>b.onclick=()=>{sound.unlock();sound.play('click');if(game.finished){toast('關卡已結束，重新開始或挑戰另一座花園吧！');return}game.select(game.selectedType===b.dataset.tower?null:b.dataset.tower);if(innerWidth<900&&game.selectedType)$('#scene').scrollIntoView({behavior:'smooth',block:'center'})});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{sound.unlock();if(Number(b.dataset.level)!==game.levelIndex)confirmReset(Number(b.dataset.level))});$('#start-wave').onclick=()=>{sound.unlock();game.startWave()};$('#pause').onclick=()=>game.togglePause();$('#paused-cover').onclick=()=>game.togglePause();$('#speed').onclick=()=>{game.toggleSpeed();sound.play('click')};$('#restart').onclick=()=>confirmReset(game.levelIndex);$('#view-3d').onclick=()=>game.setView('3d');$('#view-2d').onclick=()=>game.setView('2d');$('#reset-camera').onclick=()=>{game.camera.zoom=1;game.camera.updateProjectionMatrix();game.setView('3d')};$('#zoom-in').onclick=()=>game.zoom(.15);$('#zoom-out').onclick=()=>game.zoom(-.15)}
overlay.addEventListener('click',e=>{if(e.target===overlay)closeModal()});
document.addEventListener('keydown',e=>{if(!overlay.hidden){if(e.code==='Escape')closeModal();if(e.code==='Tab'){const focusables=[...$('#modal').querySelectorAll('button:not(:disabled),input')];const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return}if(!game||['INPUT','TEXTAREA'].includes(e.target.tagName)||e.repeat)return;if(e.code==='Space'){e.preventDefault();game.togglePause()}else if(e.code==='Enter'&&(!e.target.closest('button')||e.target.id==='start-wave')){e.preventDefault();sound.unlock();game.startWave()}else if(e.code==='Escape')game.select(null);else if(['Digit1','Digit2','Digit3'].includes(e.code)&&!game.finished){sound.unlock();game.select(['pea','mushroom','frost'][Number(e.code.at(-1))-1])}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&!game.paused&&!game.finished){game.paused=true;game.emit()}});
// The development-only handle makes real browser simulations inspectable without affecting production.
if(import.meta.env.DEV)window.__garden={game,sound,LEVELS,TOWERS};
